Feature: Fields

  Background:
    Given I have fields:
      | field_id | site_id | group_id | field_name      | field_label | field_instructions | field_type | field_list_items | field_pre_populate | field_pre_channel_id | field_pre_field_id | field_ta_rows | field_maxl | field_required | field_text_direction | field_search | field_is_hidden | field_fmt | field_show_fmt | field_order | field_content_type | field_settings                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | 1        | 1       | 1        | page_body       | Body        |                    | text       |                  | 0                  | 0                    | 0                  | 6             | 128        | n              | ltr                  | y            | n               | xhtml     | n              | 2           | any                | YTo3OntzOjY6Ind5dmVybiI7YTo3OntzOjIwOiJmaWVsZF9kaXNwbGF5X2hlaWdodCI7czozOiIyMDAiO3M6MjA6ImZpZWxkX3Jlc2l6ZV9lbmFibGVkIjtzOjM6InllcyI7czoyMDoiZmllbGRfdGV4dF9kaXJlY3Rpb24iO3M6MzoibHRyIjtzOjE0OiJhbGxvd19pbWdfdXJscyI7czozOiJ5ZXMiO3M6MTQ6ImF1dG9fbGlua191cmxzIjtzOjM6InllcyI7czo3OiJ0b29sYmFyIjthOjk6e3M6NzoiZ3JvdXBfMSI7czoxOiIxIjtzOjc6Imdyb3VwXzIiO3M6MToiMSI7czo3OiJncm91cF8zIjtzOjE6IjEiO3M6NzoiZ3JvdXBfNCI7czoxOiIxIjtzOjc6Imdyb3VwXzUiO3M6MToiMSI7czo3OiJncm91cF82IjtzOjE6IjEiO3M6NzoiZ3JvdXBfNyI7czoxOiIxIjtzOjc6Imdyb3VwXzgiO3M6MToiMSI7czo3OiJncm91cF85IjtzOjE6IjEiO31zOjEyOiJ1cGxvYWRfcHJlZnMiO2E6MTp7aTowO3M6MzoiYWxsIjt9fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ== |
      | 2        | 1       | 1        | page_header     | Header      |                    | text       |                  | 0                  | 0                    | 0                  | 6             | 128        | n              | ltr                  | n            | n               | none      | n              | 1           | any                | YTo3OntzOjE4OiJmaWVsZF9jb250ZW50X3R5cGUiO3M6MzoiYWxsIjtzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | 3        | 1       | 1        | page_checkboxes | Checkboxes  |                    | checkboxes |                  | n                  | 0                    | 0                  | 6             | 128        | n              | ltr                  | n            | n               | none      | n              | 8           | any                | YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | 4        | 1       | 1        | page_grid       | Grid Field  |                    | grid       |                  | 0                  | 0                    | 0                  | 6             | 128        | n              | ltr                  | n            | n               | xhtml     | n              | 1           | any                | YTo4OntzOjEzOiJncmlkX21pbl9yb3dzIjtpOjA7czoxMzoiZ3JpZF9tYXhfcm93cyI7czowOiIiO3M6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

    Given I have a grid table with the id "4" with columns "col_id_1,col_id_2"

    Given I have grid columns:
      | col_id | field_id | content_type | col_order | col_type     | col_label    | col_name     | col_instructions | col_required | col_search | col_width | col_settings                                                                                                                                                                                               |
      | 1      | 4        | channel      | 0         | text         | Name         | name         |                  | n            | n          | 0         | {"field_maxl":"256","field_fmt":"none","field_text_direction":"ltr","field_content_type":"all","field_required":"n"}                                                                       |
      | 2      | 4        | channel      | 1         | relationship | Relationship | relationship |                  | n            | n          | 0         | {"channels":[],"expired":0,"future":0,"categories":[],"authors":[],"statuses":[],"limit":"100","order_field":"title","order_dir":"asc","allow_multiple":1,"field_required":"n"} |

  Scenario: I need to test validity of custom fields
    When default language is "en"
    Then I should get "text" fields as array
    And I should have 2 "text" fields
    Then I want a list of fields as select menu options
